import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import "../../styles/main.scss";
import argentBankLogo from '../../designs/img/argentBankLogo.png';
import iconMoney from "../../designs/img/icon-money.png";
import iconChat from "../../designs/img/icon-chat.png";
import iconSecurity from "../../designs/img/icon-security.png";
var Home = function () {
    return (_jsxs(_Fragment, { children: [_jsxs("nav", { className: "home-nav", children: [_jsxs(Link, { to: "/", className: "main-nav-logo", children: [_jsx("img", { className: "home-nav-logo-image", src: argentBankLogo, alt: "Argent Bank Logo" }), _jsx("h1", { className: "sr-only", children: "Argent Bank" })] }), _jsxs("div", { className: 'home-nav-container', children: [_jsx(Link, { to: "/sign-in", className: "home-nav-item", children: "Sign In" }), _jsx(Link, { to: "/sign-up", className: 'home-nav-item', children: "Sign Up" })] })] }), _jsxs("main", { children: [_jsx("div", { className: "hero", children: _jsxs("section", { className: "hero-content", children: [_jsx("h2", { className: "sr-only", children: "Promoted Content" }), _jsx("p", { className: "subtitle", children: "No fees." }), _jsx("p", { className: "subtitle", children: "No minimum deposit." }), _jsx("p", { className: "subtitle", children: "High interest rates." }), _jsx("p", { className: "text", children: "Open a savings account with Argent Bank today!" })] }) }), _jsxs("section", { className: "features", children: [_jsx("h2", { className: "sr-only", children: "Features" }), _jsxs("div", { className: "feature-item", children: [_jsx("img", { src: iconChat, alt: "Chat Icon", className: "feature-icon" }), _jsx("h3", { className: "feature-item-title", children: "You are our #1 priority" }), _jsx("p", { children: "Need to talk to a representative? You can get in touch through our 24/7 chat or through a phone call in less than 5 minutes." })] }), _jsxs("div", { className: "feature-item", children: [_jsx("img", { src: iconMoney, alt: "Chat Icon", className: "feature-icon" }), _jsx("h3", { className: "feature-item-title", children: "More savings means higher rates" }), _jsx("p", { children: "The more you save with us, the higher your interest rate will be!" })] }), _jsxs("div", { className: "feature-item", children: [_jsx("img", { src: iconSecurity, alt: "Chat Icon", className: "feature-icon" }), _jsx("h3", { className: "feature-item-title", children: "Security you can trust" }), _jsx("p", { children: "We use top of the line encryption to make sure your data and money is always safe." })] })] })] }), _jsx("footer", { className: "footer", children: _jsx("p", { className: "footer-text", children: "Copyright 2020 Argent Bank" }) })] }));
};
export default Home;
